/**
 * All UI strings in one place. English-only for the firmware edition; this module
 * is the extraction point if translations are ever needed.
 */
export const S = {
  appName: 'MeshCommander',
  connecting: 'Connecting',
  connected: 'Connected',
  disconnected: 'Disconnected',
  error: 'Error',

  navSystem: 'System Status',
  navHardware: 'Hardware Information',
  navEvents: 'Event Log',
  navAudit: 'Audit Log',
  navStorage: 'Storage',
  navNetwork: 'Network Settings',
  navUsers: 'User Accounts',
  navSol: 'Serial-over-LAN',
  navKvm: 'Remote Desktop',
  navInternet: 'Internet Settings',
  navDefense: 'System Defense',
  navPresence: 'Agent Presence',
  navScripts: 'Script Editor',
  navSubs: 'Subscriptions',
  navAlarms: 'Wake Alarms',

  powerControl: 'Power Control',

  general: 'General',
  processor: 'Processor',
  memory: 'Memory',
  storageDevices: 'Storage Devices',
  operatingSystem: 'Operating System',

  refresh: 'Refresh',
  add: 'Add',
  remove: 'Remove',
  close: 'Close',
  ok: 'OK',
  cancel: 'Cancel',
  clear: 'Clear',
  viewAll: 'View All',
  details: 'Details',

  loading: 'Loading',
  noData: 'No data',
  username: 'Username',
  password: 'Password',
  realm: 'Realm',
  permission: 'Permission',
  enabled: 'Enabled',
  disabled: 'Disabled',
  actions: 'Actions',

  time: 'Time',
  severity: 'Severity',
  source: 'Source',

  advisoryLink: 'Intel Security Advisory INTEL-SA-00625',

  wireless: 'Wireless',
  wired: 'Wired',
  macAddress: 'MAC Address',
  domain: 'Domain',

  totalCapacity: 'Total Capacity',
  freeSpace: 'Free Space',
  used: 'Used',
  filesystem: 'File System',

  noAccounts: 'No user accounts configured',
  addUser: 'Add User Account',
  removeUser: 'Remove User Account',
  updateUser: 'Update User Account',
  vulnerableVersionVersion: 'This computer\'s AMT firmware ({0}) is affected by a security advisory. Update the firmware.',
  // --- Hardware Information ---
  platform: 'Platform',
  baseboard: 'Baseboard',
  bios: 'BIOS',
  biosVendor: 'Vendor',
  version: 'Version',
  serialNumber: 'Serial number',
  systemId: 'System ID',
  assetTag: 'Asset tag',
  replaceable: 'Replaceable?',
  productName: 'Product name',
  releaseDate: 'Release date',
  manufacturer: 'Manufacturer',
  computerModel: 'Computer model',
  family: 'Family',
  maxSocketSpeed: 'Maximum socket speed',
  status: 'Status',
  memoryModule: 'Memory module',
  bankLabel: 'Bank label',
  capacity: 'Size',
  formFactor: 'Form factor',
  type: 'Type',
  partNumber: 'Part number',
  storageMedia: 'Storage media',
  model: 'Model',
  battery: 'Battery',
  deviceName: 'Device name',
  manufactureDate: 'Manufacture date',
  designCapacity: 'Design capacity',
  designVoltage: 'Design voltage',
  otherInfo: 'Other info',
  class: 'Class',
  elementName: 'Element name',
  allComponents: 'All Components',
  hardwareNote: 'Hardware information is gathered at system boot time.',
  unknown: 'Unknown',
  yes: 'Yes',
  no: 'No',

  // --- Event Log ---
  events: 'Events',
  eventNumber: 'Event',
  description: 'Description',
  deviceAddress: 'Device address',
  entity: 'Entity',
  entityInstance: 'Entity instance',
  eventData: 'Data',
  offset: 'Offset',
  sensorType: 'Sensor type',
  sourceType: 'Source type',
  sensorNumber: 'Sensor number',
  eventFilter: 'Filter',
  clearEventLog: 'Clear Log',
  clearEventLogConfirm: 'Clear event log?',
  freezeLog: 'Freeze Log',
  unfreezeLog: 'Un-freeze Log',
  logStatus: 'Log status',
  maximumRecords: 'Maximum records',
  records: 'Records',
  allEvents: 'All Events',
  noEvents: 'No event log entries',
  eventDetails: 'Event #{0} Details',
  critical: 'Critical',
  warning: 'Warning',
  information: 'Information',
  invalidData: 'Invalid Data',
  ocrError: 'One Click Recovery: {0}',
  eraseSsdError: 'Got an error erasing Device SSD',
  eraseTpmUnsupported: 'Erasing Device TPM is not supported',
  reachedMaxCounter: 'Reached Max Counter',
  oemFirmwareError: 'OEM Specific Firmware Error event',
  ocrBootOption: 'One Click Recovery: CSME Boot Option {0}:{1} added successfully',
  ocrProgress: 'One Click Recovery: {0}',
  ocrUnknownProgress: 'One Click Recovery: Unknown progress event {0}',
  deviceSsd: 'SSD',
  deviceTpm: 'TPM',
  deviceBiosGoldenConfig: 'BIOS Reload of Golden Config',
  startedErasing: 'Started erasing Device {0}',
  erasingEnded: 'Erasing Device {0} ended successfully',
  beginningPlatformErase: 'Beginning Platform Erase',
  clearReservedParameters: 'Clear Reserved Parameters',
  allSettingDecremented: 'All setting decremented',
  oemFirmwareProgress: 'OEM Specific Firmware Progress event',
  watchdogState: 'Agent watchdog {0}-{1}-... changed to {2}',
  notStarted: 'Not Started',
  stopped: 'Stopped',
  running: 'Running',
  expired: 'Expired',
  suspended: 'Suspended',
  caseIntrusion: 'Case intrusion',
  solSessionEstablished: 'A remote Serial Over LAN session was established.',
  solSessionFinished: 'Remote Serial Over LAN session finished. User control was restored.',
  iderSessionEstablished: 'A remote IDE-Redirection session was established.',
  iderSessionFinished: 'Remote IDE-Redirection session finished. User control was restored.',
  filterInbound: 'All received packet filter was matched on {0} interface.',
  filterOutbound: 'All outbound packet filter was matched on {0} interface.',
  filterSpoofed: 'Spoofed packet filter was matched on {0} interface.',
  filterMatched: 'Filter {0} was matched on {1} interface.',
  securityPolicyTx: 'Security policy invoked. Some or all network traffic (TX) was stopped.',
  securityPolicyRx: 'Security policy invoked. Some or all network traffic (RX) was stopped.',
  securityPolicy: 'Security policy invoked.',
  userRemoteConnectionRequest: 'User request for remote connection.',
  hwaError: 'HWA Error: general error',
  authFailed: 'Authentication failed {0} times. The system may be under attack.',
  noBootableMedia: 'No bootable media',
  osLockupOrPowerInterrupt: 'Operating system lockup or power interrupt',
  biosPostWatchdog: 'BIOS POST (Power On Self-Test) Watchdog Timeout.',
  systemBootFailure: 'System boot failure',
  firmwareStarted: 'System firmware started (at least one CPU is properly executing).',
  unknownSensorType: 'Unknown Sensor Type #{0}',

  // --- Network Settings ---
  networkNote: 'Changing network settings may cause this page to become unavailable.',
  generalSettings: 'General Settings',
  nameAndDomain: 'Name & Domain',
  sharedWithOs: 'shared with OS',
  differentFromOs: 'different from OS',
  dynamicDns: 'Dynamic DNS',
  ddnsPeriodic: 'Enabled every {0} minutes, TTL is {1} minutes',
  ddnsByDhcp: 'Update by DHCP server',
  wiredInterface: 'Wired Interface',
  wirelessInterface: 'Wireless Interface',
  linkState: 'Link state',
  linkUp: 'Link is up',
  linkDown: 'Link is down',
  linkPolicy: 'Link policy',
  availableIn: 'Available in: {0}',
  notAvailable: 'Not available',
  state: 'State',
  radioState: 'Radio State',
  enabledInS0: 'Enabled in S0',
  enabledInS0SxAc: 'Enabled in S0, Sx/AC',
  onConnected: 'On, Connected',
  off: 'Off',
  onDisconnected: 'On, Disconnected',
  localProfileSync: 'Local WIFI Profile Sync',
  uefiWifiCoex: 'UEFI WiFi CoEx Profile sharing',
  unavailable: 'Unavailable',
  respondToPing: 'Respond to ping',
  icmpResponse: 'ICMP response',
  rmcpResponse: 'RMCP response',
  icmpAndRmcp: 'ICMP & RMCP response',
  ipv4State: 'IPv4 state',
  autoDhcp: 'Automatic using DHCP server',
  staticIp: 'Static IP address',
  ipSync: 'IP sync with OS',
  ipv4Address: 'IPv4 address',
  ipv4GatewayMask: 'IPv4 gateway / Mask',
  ipv4Dns: 'IPv4 domain name server',
  ipv6State: 'IPv6 state',
  ipv6Disabled: 'Disabled',
  ipv6Automatic: 'Enabled, Automatic addresses',
  ipv6AutomaticManual: 'Enabled, Automatic & manual addresses',
  ipv6Address: 'IPv6 address',
  ipv6Router: 'IPv6 default router',
  ipv6Dns: 'IPv6 domain name server',
  noneValue: 'None',
  ssid: 'SSID',
  wirelessProfiles: 'Wireless Profiles',
  noWirelessProfiles: 'No Wireless Profiles Present',
  profileName: 'Profile Name',
  authentication: 'Authentication',
  encryption: 'Encryption',
  priority: 'Priority',
  other: 'Other',
  open: 'Open',
  sharedKey: 'Shared Key',
  wpaPsk: 'WPA PSK',
  wpa8021x: 'WPA IEEE 802.1x',
  wpa2Psk: 'WPA2 PSK',
  wpa28021x: 'WPA2 IEEE 802.1x',
  wpa3Sae: 'WPA3 SAE IEEE 802.1x',
  wpa3Owe: 'WPA3 OWE IEEE 802.1x',
  wep: 'WEP',
  tkipRc4: 'TKIP-RC4',
  ccmpAes: 'CCMP-AES',
  // --- Storage ---
  name: 'Name',
  application: 'Application',
  download: 'Download',
  storageDevice: 'Device',
  mountPoint: 'Mount Point',
  noFiles: 'No files found.',
  storageLoadFailed: 'Unable to load storage data (ERR{0}).',
  storageDeleteFailed: 'Unable to delete file (ERR{0}); check that the computer is powered on.',

  // --- User Accounts ---
  edit: 'Edit',
  enable: 'Enable',
  disable: 'Disable',
  administrator: 'Administrator',
  auditor: 'Auditor',
  none: 'None',
  manyRealms: '{0} realms',
  confirmPassword: 'Confirm Password',
  passwordRules: 'Minimum 8 characters with upper, lowercase, 0-9, and one of !@#$%^&*()+-',
  grantedPermissions: 'Granted Permissions',
  showHiddenAccounts: 'Show hidden accounts',
  hideHiddenAccounts: 'Hide hidden accounts',
  accountDetails: 'Account {0}',
  removeUserConfirm: 'Remove the account {0}?',

  // --- Audit Log ---
  auditSettings: 'Audit Log Settings',
  auditState: 'State',
  auditStorage: 'Storage',
  auditRecords: '{0} record(s), {1}% free',
  overwritePolicy: 'Overwrite policy',
  wrapsWhenFull: 'Wraps when full',
  neverOverwrites: 'Never overwrites',
  auditEvents: 'Audit Events',
  initiator: 'Initiator',
  event: 'Event',
  address: 'Address',
  extendedData: 'Extended Data',
  dataValues: 'Data Values',
  dataString: 'Data String',
  filter: 'Filter',
  clearLog: 'Clear Log',
  clearAuditLogConfirm: 'Clear audit log?',
  noAuditEvents: 'No audit log events found.',
  auditEventDetails: 'Audit Event Details',
  initiatorLocal: 'Local',
  initiatorKvm: 'KVM Default Port',
  locked: 'Locked',
  almostFull: 'Almost Full',
  full: 'Full',
  noKey: 'No Key',
  lock: 'Lock',
  unlock: 'Unlock',

  // --- System Defense ---
  action: 'Action',
  count: 'Count',
  packet: 'packet',
  packets: 'packets',
  allow: 'Allow',
  drop: 'Drop',
  allowCount: 'Allow, Count',
  dropCount: 'Drop, Count',
  rateLimit: 'Rate limit',
  eventOnMatch: 'Event on match',
  doNothing: 'Do nothing',
  eventLog: 'Event Log',
  allIpPackets: 'All IP Packets',
  allArpPackets: 'All ARP Packets',
  allEthernetProtocol: 'All Ethernet Protocol',
  allIpProtocol: 'All IP Protocol',
  ipv4: 'IPv4',
  ipv6: 'IPv6',
  direction: 'Direction',
  outbound: 'Outbound / Transmit',
  inbound: 'Inbound / Receive',
  matchingTraffic: 'Matching traffic',
  ethernetTraffic: 'Ethernet traffic',
  ipTraffic: 'IP traffic',
  ethernetIpFilter: 'Ethernet IP packet filter',
  ethernetArpFilter: 'Ethernet ARP packet filter',
  ipv4Filter: 'IPv4 packet filter',
  ipv6Filter: 'IPv6 packet filter',
  packetsPerSecond: 'Packets / second',
  addFilter: 'Add Filter',
  defaultPolicyDialog: 'Default System Defense Policy',
  defaultWiredPolicy: 'Default Wired Policy',
  defaultWirelessPolicy: 'Default Wireless Policy',
  policiesHeading: 'Manage Intel(R) AMT system defense policies.',
  filtersHeading: 'Manage Intel(R) AMT system defense filters.',
  noPolicies: 'No system defense policies found.',
  noFilters: 'No system defense filters found.',
  policyName: 'Policy name',
  precedence: 'Precedence',
  defaultTxAction: 'Default TX action',
  defaultRxAction: 'Default RX action',

  // --- Internet Settings ---
  accessName: 'Access name',
  port: 'Port',
  commonName: 'Common name',
  domains: 'domains',
  policyKinds: {
    User: 'User initiated connection',
    Alert: 'Alert initiated connection',
    Periodic: 'Periodic connection',
  },
  enabledDomains: 'Enabled, {0}',
  biosEnabled: 'BIOS enabled',
  osEnabled: 'OS enabled',
  biosOsEnabled: 'BIOS and OS enabled',
  serversHeading: 'Manage Intel(R) AMT remote management servers.',
  noServers: 'No remote servers found.',
  policyRulesHeading: 'Remote access policy rules',
  noPolicyRules: 'No remote access policy rules found.',
  policyRule: 'Policy rule',
  tunnelLifetime: 'Tunnel lifetime (seconds)',
  trigger: 'Trigger',
  eachSeconds: 'each {0} seconds',
  atDaily: 'at {0} daily',
  removeServer: 'Remove Server',
  environmentDetection: 'Environment detection',
  environmentDetectionHelp:
    'Enter up to 5 intranet domain suffixes. If the computer is outside these domains, Intel(R) AMT local ports are closed and remote server connections are active.',
  noIntranetDomains: 'No intranet domains, environment detection disabled.',
  domainPlaceholder: 'intranet.org',
  userInitiationOptions: 'User initiation options',
  userInitiatedTunnel: 'User Initiated Tunnel',
  primaryServer: 'Primary server',
  secondaryServer: 'Secondary server',
  mpsType: 'Primary MPS type',
  secondaryMpsType: 'Secondary MPS type',
  cira: 'CIRA - External',
  cila: 'CILA - Internal',
  triggerType: 'Trigger type',
  triggerInterval: 'Trigger interval (seconds)',
  timeOfDay: 'Time of day (HH:MM)',

  // --- Agent Presence ---
  shuttingDown: 'Shutting Down',
  notApplicable: 'Not Applicable',
  enabledButOffline: 'Enabled but Offline',
  inTest: 'In Test',
  deferred: 'Deferred',
  quiesce: 'Quiesce',
  starting: 'Starting',
  osBootProcess: 'Operating System Boot Process',
  osShutdownProcess: 'Operating System Shutdown Process',
  firmwareBootProcess: 'Firmware Boot Process',
  biosBootProcess: 'BIOS Boot Process',
  serviceProcessor: 'Service Processor',
  anyState: 'Any State',
  seconds: 'seconds',
  maxWatchdogs: 'Maximum watchdogs',
  maxActions: 'Maximum total actions',
  currentState: 'Current state',
  enabledState: 'Enabled state',
  monitoredEntity: 'Monitored entity',
  startupInterval: 'Startup interval',
  timeoutInterval: 'Timeout interval',
  watchdogsHeading: 'Manage Intel(R) AMT agent presence watchdogs.',
  actionsHeading: 'Watchdog actions',
  noWatchdog: 'No agent presence watchdog found.',
  noWatchdogActions: 'No watchdog actions found.',
  addWatchdogAction: 'Add Action',
  deleteWatchdogActions: 'Delete Actions',
  removeWatchdog: 'Remove Watchdog',
  policyAction: 'Action',
  oldState: 'Old state',
  newState: 'New state',
  actionSd: 'Secure Delete',
  actionEac: 'EAC',
  from: 'From state',
  to: 'To state',
  writeToEventLog: 'Write to event log',
  eventOnTransition: 'Event on transition',
  confirmDeleteActions: 'Delete all actions for this watchdog?',

  // --- Wake Alarms ---
  alarmsHeading: 'Manage wake alarms.',
  noWakeAlarms: 'No wake alarms registered.',
  wakeTime: 'Wake time',
  repeat: 'Interval',
  repeatHint: 'Repeat (days-hours-minutes)',
  afterWake: 'After wake',
  deleteAlarm: 'Delete alarm',
  keepAlarm: 'Keep alarm',
  deleteWhenDone: 'Delete when done',
  addAlarm: 'Add Alarm',
  removeAllAlarms: 'Remove all wake alarms',
  confirmRemoveAll: 'Confirm removal of all wake alarms?',
  alarmDate: 'Date',
  alarmTime: 'Time',
  days: 'days',
  hours: 'hours',
  minutes: 'minutes',

  // --- Event Subscriptions ---
  destination: 'Destination',
  filterLabel: 'Filter',
  deliveryMode: 'Delivery mode',
  push: 'Push',
  pushWithAck: 'Push with ACK',
  pull: 'Pull',
  subscribersHeading: 'Manage event subscribers.',
  noSubscriptions: 'No subscriptions found.',
  subscription: 'Subscription',
  iderSession: 'IDE-R Session',
  iderIdle: 'No IDE-R session',
  iderDropHint: 'Drop an image, or choose:',
  iderStart: 'Start IDE-R Session',
  iderStop: 'Stop IDE-R Session',
  iderDiskMap: 'Disk Map',
  iderEject: 'Eject',
  iderFloppy: 'Floppy (.img)',
  iderCdrom: 'CDROM (.iso)',
  iderFloppyLabel: 'Floppy',
  iderCdromLabel: 'CDROM',
  iderPerBlock: 'bytes per block',
  iderStartMode: 'Session Start',
  iderOnReboot: 'On next boot',
  iderGraceful: 'Graceful',
  iderNow: 'Immediate',
  iderIn: 'in',
  iderOut: 'out',
  iderNoImage: 'At least one disk image must be selected.',
  iderBadFloppy: 'Invalid .img file. Size must be a multiple of 512 bytes.',
  iderBadCdrom: 'Invalid .iso file. Size must be a multiple of 2048 bytes.',
  kvmConnect: 'Connect',
  kvmDisconnect: 'Disconnect',
  kvmSetup: 'Setting up...',
  kvmFullscreen: 'Fullscreen',
  kvmExitFullscreen: 'Exit fullscreen',
  kvmRotateLeft: 'Rotate left',
  kvmRotateRight: 'Rotate right',
  kvmFocusAll: 'Focus all',
  kvmFocus: 'Focus',
  kvmRotate: 'Rotation',
  kvmFocusSmall: 'Focus small',
  kvmFocusLarge: 'Focus large',
  kvmSettings: 'Settings...',
  kvmViewerSettings: 'Remote Desktop Settings',
  kvmPixelFormat: 'Pixel format',
  kvmShowLocalCursor: 'Show local mouse cursor',
  kvmShowCad: 'Show Ctrl-Alt-Del',
  kvmLimitFrameRate: 'Limit frame rate',
  kvmNoMouseRotate: 'Do not rotate mouse',
  kvmReverseWheel: 'Reverse mouse wheel',
  kvmEncRle8: 'RLE8, 256 Colors',
  kvmEncRle16: 'RLE16, 64k Colors',
  kvmEncRaw8: 'RAW8, 256 Colors',
  kvmEncRaw16: 'RAW16, 16k Colors',
  kvmEncRle8Gray: 'RLE8G, 256 Grays',
  kvmEncRle4Gray: 'RLE4G, 16 Grays',
  kvmDisplay: 'Display',
  kvmKeyboard: 'Keyboard',
  kvmIder: 'IDE-R',
  kvmSwitchTo: 'Switch to display {0}',
  kvmCad: 'Ctrl-Alt-Del',
  kvmType: 'Type',
  kvmSpecialKey: 'Special key',
  kvmViewOnly: 'View only',
  kvmViewOnlyHint: 'Show the remote screen without sending any keyboard or mouse input.',
  kvmBlankScreen: 'Blank screen',
  kvmBlankScreenHint: 'Turn the remote monitor off through Intel AMT screen blanking.',
  kvmBlankUnsupported: 'Intel AMT refused screen blanking on this device, so the monitor is unchanged.',
  kvmTypeDialogTitle: 'Remote Keyboard Entry',
  kvmTypeDialogHint: 'Enter text and click OK to remotely type it using a US english keyboard. Make sure to place the remote cursor at the correct position before proceeding.',
  kvmTypeDialogLabel: 'Text to type',
  kvmEnableTitle: 'Enable Remote Desktop',
  kvmRedirDisabled: 'Intel AMT redirection port or KVM feature is disabled. Click here to enable it.',
  kvmBusy: 'The remote device is busy, a session may already be open.',
  kvmUnsupported: 'The device indicated that this type of connection is not supported.',
  kvmLinkLost: 'KVM disconnection, this may indicate that Intel AMT is unable to capture the display (try the 8-bit RLE encoding), or an unsupported GPU.',
  kvmBufferOverflow: 'KVM disconnection that may be due to the display size and resolution being too large for the Intel AMT KVM buffer. Try the 8-bit RLE encoding or reduce the display resolution.',
  kvmNotPoweredOn: 'The remote computer is not powered on.',
  kvmKeyWin: 'Win',
  kvmKeyWinDown: 'Win+Down',
  kvmKeyWinUp: 'Win+Up',
  kvmKeyWinL: 'Win+L',
  kvmKeyWinM: 'Win+M',
  kvmKeyWinR: 'Win+R',
  kvmKeyWinLeft: 'Win+Left',
  kvmKeyWinRight: 'Win+Right',
  kvmKeyShiftWinM: 'Shift+Win+M',
  kvmKeyAltTab: 'Alt-Tab',
  kvmKeyAltF4: 'Alt-F4',
  kvmKeyCtrlW: 'Ctrl-W',
  kvmKeyF1: 'F1',
  kvmKeyF2: 'F2',
  kvmKeyF3: 'F3',
  kvmKeyF4: 'F4',
  kvmKeyF5: 'F5',
  kvmKeyF6: 'F6',
  kvmKeyF7: 'F7',
  kvmKeyF8: 'F8',
  kvmKeyF9: 'F9',
  kvmKeyF10: 'F10',
  kvmKeyF11: 'F11',
  kvmKeyF12: 'F12',
  kvmKeyEnter: 'Enter',
  solConnect: 'Connect',
  solDisconnect: 'Disconnect',
  solSettingUp: 'Setting up',
  solKeyHint: 'Click here, then type to send keystrokes to the device',
  solScreen: 'Terminal output',
  solSettings: 'Terminal settings',
  solLineEnding: 'Line ending',
  solEncoding: 'Encoding',
  solFxKeys: 'F-keys',
  solSize: 'Size',
  solCrLf: 'CR+LF',
  solLf: 'LF',
  solFxIntel: 'Intel (F10 = ESC+[OM)',
  solFxAlt: 'Alternate (F10 = ESC+0)',
  solFxVt100: 'VT100+ (F10 = ESC+[OY)',
  solEncUtf8: 'UTF-8',
  solEncAscii: 'Extended Ascii',
  solEncIntel: 'Intel Ascii',
  scriptViewEditor: 'View Editor',
  scriptViewBuilder: 'View Builder',
  scriptNew: 'New...',
  scriptLoad: 'Load...',
  scriptSave: 'Save...',
  scriptRestart: 'Restart',
  scriptContinue: 'Continue',
  scriptBreak: 'Break',
  scriptStep: 'Step',
  scriptConsole: 'Console',
  scriptVariables: 'Variables',
  scriptFilterBlocks: 'Filter blocks...',
  scriptStopped: 'Stopped',
  scriptRunning: 'Running',
  scriptPaused: 'Paused',
  scriptStoppedNoScript: 'Stopped, no script',
  scriptEdit: 'Edit...',
  scriptDelete: 'Delete',
  scriptEmptyScript: 'Add blocks from the library to build your script.',
  scriptNewConfirm: 'Reset and clear the script editor?',
  scriptCompileError: 'Script Compile Error',
  scriptRunningBar: 'Running Script',
  scriptStopScript: 'Stop Script',
  scriptNotSet: 'Not set',
  scriptBinaryFile: 'Binary file, {0} bytes',
  scriptLoaded: 'Script loaded',
  kvmShowFocusTool: 'Show focus tool',
  kvmNoDisplay: 'Intel(R) AMT could not capture the display. The target may be powered off, still booting, or sitting at a disk-encryption prompt.',
} as const

/**
 * Install-from-web page strings.
 *
 * Deliberately not part of `S`: that table ships in every tier, and a feature no
 * tier preset includes must not cost the smaller tiers a byte. This object is
 * only referenced from the gated page and the gated nav entry, so it drops out
 * of every build that leaves the feature off.
 */
export const INSTALL = {
  navInstall: 'Install Firmware',
  installHint:
    'Writes a .htm.gz firmware artifact into this device\'s user flash and serves it at /index.htm. ' +
    'The artifact must be built for this console\'s feature set; a cross-origin URL has to send CORS headers.',
  artifactUrl: 'Artifact URL',
  installAction: 'Install',
  installing: 'Installing',
  installReload: 'Reload',
  installProgress: 'Block {0}: {1} of {2} bytes written.',
  installComplete: 'Firmware written. Reload the console to run it.',
  installFetchFailed: 'Could not fetch the artifact: {0}',
  installNotGzip:
    'That URL served {0} bytes that are not a gzip artifact; the console would be stored corrupt. ' +
    'A server that sends .gz files with Content-Encoding: gzip returns the decompressed console instead.',
  installFailed: 'Install failed (ERR{0}).',
  installNoCredentials: 'The browser has no cached credentials for this device; reload the device page.',
} as const

/**
 * AMT ACL realm ids, verbatim from amt-0.2.0.js RealmNames. The blank entries
 * are reserved realms the console never offers.
 */
export const REALM_NAMES: readonly string[] =
  '||Redirection||Hardware Asset|Remote Control|Storage|Event Manager|Storage Admin|Agent Presence Local|Agent Presence Remote|Circuit Breaker|Network Time|General Information|Firmware Update|EIT|LocalUN|Endpoint Access Control|Endpoint Access Control Admin|Event Log Reader|Audit Log|ACL Realm|||Local System'.split(
    '|',
  )

