/**
 * Build the site's generated inputs, then get out of the way.
 *
 * Three things have to exist before vite runs:
 *   - `public/demo/index.htm`, the console itself, built by the console's own
 *     pipeline with the demo feature set and **decompressed**: GitHub Pages
 *     cannot set `Content-Encoding`, so the shipped `.htm.gz` would arrive as
 *     opaque bytes.
 *   - `public/responses.json`, the recorded device conversation the Service
 *     Worker replays (`packages/mock/export-static.ts`).
 *   - `public/size-cache.json`, the measurement table the feature picker sums.
 *
 *   bun apps/site/scripts/prepare.ts
 */
import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { gunzipSync } from 'node:zlib'
import { marginalTable } from '@meshcommander/build-system/estimate'

const CONSOLE_DIR = new URL('../../console/', import.meta.url).pathname
const MOCK_DIR = new URL('../../../packages/mock/', import.meta.url).pathname
const PUBLIC_DIR = new URL('../public/', import.meta.url).pathname

/**
 * What the demo runs: the pages a visitor can walk without a real device.
 *
 * The Remote Desktop viewer's own features are in here as well as the page
 * itself. They cost 688 B gzipped together and they are what a visitor is
 * looking at: without `Desktop-Settings` the Display menu has no viewer
 * settings, without `DesktopRotation` no rotation, and the demo's window would
 * show a toolbar the shipped console does not have.
 */
const DEMO_FEATURES = [
  'Desktop',
  'Desktop-Multi',
  'DesktopRotation',
  'Desktop-Settings',
  'DesktopType',
  'DesktopFocus',
  'Terminal',
  'IDER',
  'HardwareInfo',
  'EventLog',
]
const DEMO_THEME = 'mesh'

/**
 * The console's own pipeline, in single-build mode: `OUT` pins the artifact and
 * the child prints one `size: <bytes>` line. Failures are fatal -- a demo that
 * silently ships a stale page is worse than a red build.
 */
const buildDemo = (): void => {
  const out = PUBLIC_DIR + 'demo/index.htm.gz'
  mkdirSync(PUBLIC_DIR + 'demo', { recursive: true })
  const proc = Bun.spawnSync(['bun', 'scripts/build-firmware.ts'], {
    cwd: CONSOLE_DIR,
    env: {
      ...process.env,
      FEATURES: DEMO_FEATURES.join(','),
      THEME: DEMO_THEME,
      BUILD_NAME: 'demo',
      OUT: out,
    },
    stdout: 'pipe',
    stderr: 'pipe',
  })
  if (proc.exitCode !== 0) {
    throw new Error(`demo console build failed (exit ${proc.exitCode}):\n${proc.stderr.toString()}`)
  }
  const size = proc.stdout.toString().match(/^size: (\d+)$/m)?.[1] ?? '?'
  writeFileSync(PUBLIC_DIR + 'demo/index.htm', gunzipSync(readFileSync(out)))
  rmSync(out)
  console.log(`demo      ${DEMO_FEATURES.length} features, theme ${DEMO_THEME}, ${size} B gzipped`)
}

/** The replay file is generated by the mock package; regenerate it there. */
const copyResponses = (): void => {
  const from = MOCK_DIR + 'static/responses.json'
  if (!existsSync(from)) {
    throw new Error(`${from} is missing -- run: bun packages/mock/export-static.ts`)
  }
  copyFileSync(from, PUBLIC_DIR + 'responses.json')
  console.log(`replay    ${from}`)
}

/**
 * Reduce the console's measurement cache to baseline + per-feature marginals.
 *
 * Every theme in the cache is written out; the picker shows the selected
 * theme's numbers and falls back to the default theme's when one is missing.
 */
const writeSizeTable = (): void => {
  const themes = ['mesh', 'midnight', 'paper', 'amber']
  const tables: Record<
    string,
    { baseline: number | null; marginal: Record<string, number>; whole: Record<string, number> }
  > = {}
  for (const theme of themes) {
    tables[theme] = marginalTable(theme)
  }
  const mesh = tables.mesh
  if (mesh?.baseline == null) {
    throw new Error(
      'no baseline measurement for the mesh theme -- run: bun packages/build-system/src/cli.ts measure',
    )
  }
  writeFileSync(PUBLIC_DIR + 'size-cache.json', JSON.stringify(tables, null, 2) + '\n')
  console.log(`sizes     ${Object.keys(mesh.marginal).length} marginals for ${themes.length} themes`)
}

buildDemo()
copyResponses()
writeSizeTable()
